### ISSUE TITLE
Error uploading big video file to Kaltura

### ISSUE THREAD

**Issue by moskiteau** [kaltura/KalturaGeneratedAPIClientsJava#5]
Hello,

I am trying to upload a big video file of 7.4G and I get the following error.

Also, note that is seems like smaller video files (anything under 2G) are uploading successfully.

The Kalktura server version is apparently 'Hercule' and is hosted at rackforcecloudvideo.com

Thank you

```
adding: test.properties(in = 251) (out= 171)(deflated 31%)
adding: 535255_546954_850_-OVP.mp4(in = 7903191249) (out= 7879985673)(deflated 0%)
adding: DemoImage.jpg(in = 10618) (out= 10249)(deflated 3%)
JUnit version 4.7
.[24 Nov 2015 10:11:15] INFO - "Starting ping test" - (SystemServiceTest.java:44) 
[24 Nov 2015 10:11:17] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
.[24 Nov 2015 10:11:18] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
.[24 Nov 2015 10:11:18] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
.[24 Nov 2015 10:11:18] INFO - "Test Update Entry" - (MediaServiceTest.java:210) 
[24 Nov 2015 10:11:20] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
[24 Nov 2015 10:11:20] INFO - "Deleting 0_hk7k6vxr" - (BaseTest.java:88) 
.[24 Nov 2015 10:11:21] INFO - "Test Add From URL" - (MediaServiceTest.java:73) 
[24 Nov 2015 10:11:22] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
[24 Nov 2015 10:11:22] INFO - "Deleting 0_0ljw3lcr" - (BaseTest.java:88) 
.[24 Nov 2015 10:11:22] INFO - "Test upload token add" - (MediaServiceTest.java:123) 
[24 Nov 2015 11:11:14] INFO - "I/O exception (java.net.SocketException) caught when processing request: Broken pipe" - (HttpMethodDirector.java:439) 
[24 Nov 2015 11:11:14] INFO - "Retrying request" - (HttpMethodDirector.java:445) 
[24 Nov 2015 11:11:14] INFO - "I/O exception (java.io.IOException) caught when processing request: Stream Closed" - (HttpMethodDirector.java:439) 
[24 Nov 2015 11:11:14] INFO - "Retrying request" - (HttpMethodDirector.java:445) 
[24 Nov 2015 11:11:14] INFO - "I/O exception (java.io.IOException) caught when processing request: Stream Closed" - (HttpMethodDirector.java:439) 
[24 Nov 2015 11:11:14] INFO - "Retrying request" - (HttpMethodDirector.java:445) 
[24 Nov 2015 11:11:14] ERROR - "Fatal transport error: Stream Closed" - (KalturaClientBase.java:365) 
java.io.IOException: Stream Closed
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:243)
	at org.apache.commons.httpclient.methods.multipart.FilePart.sendData(FilePart.java:222)
	at org.apache.commons.httpclient.methods.multipart.Part.send(Part.java:312)
	at org.apache.commons.httpclient.methods.multipart.Part.sendParts(Part.java:385)
	at org.apache.commons.httpclient.methods.multipart.MultipartRequestEntity.writeRequest(MultipartRequestEntity.java:164)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.kaltura.client.KalturaClientBase.executeMethod(KalturaClientBase.java:298)
	at com.kaltura.client.KalturaClientBase.doQueue(KalturaClientBase.java:257)
	at com.kaltura.client.services.KalturaUploadTokenService.upload(KalturaUploadTokenService.java:156)
	at com.kaltura.client.services.KalturaUploadTokenService.upload(KalturaUploadTokenService.java:116)
	at com.kaltura.client.services.KalturaUploadTokenService.upload(KalturaUploadTokenService.java:108)
	at com.kaltura.client.test.MediaServiceTest.testUploadTokenAddGivenFile(MediaServiceTest.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:98)
	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:53)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:45)
com.kaltura.client.KalturaApiException: I/O exception occured while reading request response
	at com.kaltura.client.KalturaClientBase.executeMethod(KalturaClientBase.java:366)
	at com.kaltura.client.KalturaClientBase.doQueue(KalturaClientBase.java:257)
	at com.kaltura.client.services.KalturaUploadTokenService.upload(KalturaUploadTokenService.java:156)
	at com.kaltura.client.services.KalturaUploadTokenService.upload(KalturaUploadTokenService.java:116)
	at com.kaltura.client.services.KalturaUploadTokenService.upload(KalturaUploadTokenService.java:108)
	at com.kaltura.client.test.MediaServiceTest.testUploadTokenAddGivenFile(MediaServiceTest.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:98)
	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:53)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:45)
[24 Nov 2015 11:11:14] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
[24 Nov 2015 11:11:14] INFO - "Deleting 0_aumq0edi" - (BaseTest.java:88) 
E.[24 Nov 2015 11:11:15] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
.[24 Nov 2015 11:11:15] INFO - "Starting badGet test" - (MediaServiceTest.java:242) 
[24 Nov 2015 11:11:16] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
.[24 Nov 2015 11:11:16] INFO - "Starting get test" - (MediaServiceTest.java:268) 
[24 Nov 2015 11:11:18] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
[24 Nov 2015 11:11:18] INFO - "Deleting 0_rqv4wct9" - (BaseTest.java:88) 
.[24 Nov 2015 11:11:18] INFO - "Test List" - (MediaServiceTest.java:296) 
[24 Nov 2015 11:11:23] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
[24 Nov 2015 11:11:23] INFO - "Deleting 0_d050vl6a" - (BaseTest.java:88) 
[24 Nov 2015 11:11:23] INFO - "Deleting 0_e8qs11fj" - (BaseTest.java:88) 
E.[24 Nov 2015 11:11:24] INFO - "Starting moderation test" - (MediaServiceTest.java:352) 
[24 Nov 2015 11:11:24] INFO - "Starting addFromUrl test" - (MediaServiceTest.java:357) 
[24 Nov 2015 11:11:27] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
[24 Nov 2015 11:11:27] INFO - "Deleting 0_h6bia7j1" - (BaseTest.java:88) 
.[24 Nov 2015 11:11:27] INFO - "Starting delete test" - (MediaServiceTest.java:405) 
[24 Nov 2015 11:11:30] INFO - "Cleaning up test entries after test" - (BaseTest.java:83) 
.[24 Nov 2015 11:11:30] INFO - "Starting delete test" - (MediaServiceTest.java:453)
```

**Comment by jessp01** [comment]
Hello,

This limitation stems from the fact our backend is PHP and PHP has an upload limit of 2G.
You can get around that by chunking the file into smaller files. Please see:
https://forum.kaltura.org/t/upload-over-2gb-error

**Comment by moskiteau** [comment]
Excellent, thank you
